{{- $root := . -}}
{{- range $driver := .Values.drivers -}}
{{- if and (hasSuffix  "nfs.csi.ceph.com" $driver.name) ($driver.enabled) }}
{{- $normalizedDriverName := include "normalizeDriverName" $driver.name }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $normalizedDriverName }}-nodeplugin-cr
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
{{- end }}
{{- end }}
