{{- $root := . -}}
{{- range $driver := .Values.drivers -}}
{{- if and (hasSuffix  "rbd.csi.ceph.com" $driver.name) ($driver.enabled) }}
{{- $normalizedDriverName := include "normalizeDriverName" $driver.name }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $normalizedDriverName }}-nodeplugin-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $normalizedDriverName }}-nodeplugin-cr
subjects:
- kind: ServiceAccount
  name: {{ $normalizedDriverName }}-nodeplugin-sa
  namespace: {{ $root.Release.Namespace }}
{{- end }}
{{- end }}
