kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cephfs-nodeplugin-rb
subjects:
  - kind: ServiceAccount
    name: cephfs-nodeplugin-sa
    namespace: system
roleRef:
  kind: Role
  name: cephfs-nodeplugin-r
  apiGroup: rbac.authorization.k8s.io
