name: test-ceph-csi-operator
on:
  pull_request:
    branches:
      - main
      - release-*

defaults:
  run:
    # reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell
    shell: bash --noprofile --norc -eo pipefail -x {0}

# cancel the in-progress workflow when PR is refreshed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: set up tmate session for debugging
        if: ${{ failure() || runner.debug || contains(github.event.pull_request.labels.*.name, 'debug-ci') }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false
          detached: true


      - name: Setup Minikube
        run: |
            test/scripts/github-action-helper.sh install_minikube_with_none_driver

      - name: print k8s cluster status
        run: |
            kubectl get nodes

      - name: use local disk
        run: test/scripts/github-action-helper.sh use_local_disk

      - name: create ceph cluster
        run: test/scripts/github-action-helper.sh deploy_rook

      - name: test ceph-csi-operator
        run: test/scripts/test-ceph-csi-operator.sh
