name: Test Charts

on:
  pull_request:

permissions:
  contents: read

jobs:
  test-helm:
    name: helm charts
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod

      - name: Setup Minikube
        run: |
            test/scripts/github-action-helper.sh install_minikube_with_none_driver
      - name: print k8s cluster status
        run: |
            kubectl get nodes
      - name: use local disk
        run: test/scripts/github-action-helper.sh use_local_disk

      - name: create ceph cluster
        run: test/scripts/github-action-helper.sh deploy_rook

      - name: Prepare ceph-csi-operator
        run: |
          IMAGE_TAG=test make docker-build

      - name: Install helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Verify helm installation
        run: helm version

      - name: Lint operator helm chart
        run: |
          helm lint ./deploy/charts/ceph-csi-operator

      - name: Install operator helm chart
        run: |
          helm install csi-operator ./deploy/charts/ceph-csi-operator --create-namespace --namespace ceph-csi-operator-system --set controllerManager.manager.image.tag=test

      - name: Check operator helm release status
        run: |
          helm status csi-operator --namespace ceph-csi-operator-system

      - name: Check operator is running
        run: |
          for i in {1..180}; do kubectl get pods -l app.kubernetes.io/name=ceph-csi-operator -n ceph-csi-operator-system -o jsonpath='{.items[0].status.phase}' | grep -q "Running" && exit 0 || sleep 1; done; echo "Pod not running after 3 minutes"; exit 1

      - name: Patch operator to watch csi driver namespace
        run: |
          kubectl patch deployment csi-operator-ceph-csi-operator-controller-manager -nceph-csi-operator-system --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/env/2/value", "value": "csi-driver"}]'

      - name: Lint csi driver helm chart
        run: |
          helm lint ./deploy/charts/ceph-csi-drivers

      - name: Install csi driver helm chart
        run: |
          helm install csi-driver ./deploy/charts/ceph-csi-drivers --create-namespace --namespace csi-driver

      - name: Check csi driver helm release status
        run: |
          helm status csi-driver --namespace csi-driver

      - name: Check csi pods are running
        run: |
          for i in {1..180}; do
          if [ $(kubectl get pods -n csi-driver --field-selector=status.phase=Running --no-headers | wc -l) -eq 6 ]; then
            exit 0;
          fi
            sleep 1;
          done;
          kubectl get pods,deployment,daemonset,replicaset -oyaml -n csi-driver
          kubectl get pods,deployment,daemonset,replicaset -n csi-driver
          kubectl logs -l app.kubernetes.io/instance=ceph-csi-operator -nceph-csi-operator-system
          echo "Pod(s) not running after 3 minutes";
          exit 1;
